"""Initial migration

Revision ID: 639d246bd433
Revises: 
Create Date: 2026-06-09 13:03:58.473101

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '639d246bd433'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_users_username'), ['username'], unique=True)

    op.create_table('filaments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('type', sa.String(length=100), nullable=False),
    sa.Column('color', sa.String(length=50), nullable=False),
    sa.Column('starting_weight', sa.Float(), nullable=False),
    sa.Column('current_weight', sa.Float(), nullable=False),
    sa.Column('is_archived', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('archived_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('filaments', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_filaments_is_archived'), ['is_archived'], unique=False)
        batch_op.create_index(batch_op.f('ix_filaments_user_id'), ['user_id'], unique=False)

    op.create_table('print_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('filament_id', sa.Integer(), nullable=False),
    sa.Column('weight_used', sa.Float(), nullable=False),
    sa.Column('print_name', sa.String(length=200), nullable=False),
    sa.Column('component_name', sa.String(length=200), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['filament_id'], ['filaments.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('print_history', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_print_history_filament_id'), ['filament_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_print_history_timestamp'), ['timestamp'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('print_history', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_print_history_timestamp'))
        batch_op.drop_index(batch_op.f('ix_print_history_filament_id'))

    op.drop_table('print_history')
    with op.batch_alter_table('filaments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_filaments_user_id'))
        batch_op.drop_index(batch_op.f('ix_filaments_is_archived'))

    op.drop_table('filaments')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_username'))
        batch_op.drop_index(batch_op.f('ix_users_email'))

    op.drop_table('users')
    # ### end Alembic commands ###
