"""Add multicolor_print_id to print_history

Revision ID: a3f7b9e2c4d1
Revises: 8a4c5bcc98f5
Create Date: 2026-06-10 10:30:00.000000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a3f7b9e2c4d1'
down_revision = '8a4c5bcc98f5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('print_history', schema=None) as batch_op:
        batch_op.add_column(sa.Column('multicolor_print_id', sa.String(length=36), nullable=True))
        batch_op.create_index(batch_op.f('ix_print_history_multicolor_print_id'), ['multicolor_print_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('print_history', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_print_history_multicolor_print_id'))
        batch_op.drop_column('multicolor_print_id')

    # ### end Alembic commands ###
