"""Add color_hex field to filaments

Revision ID: ccf5a8f4bc3b
Revises: 639d246bd433
Create Date: 2026-06-09 13:38:25.568686

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ccf5a8f4bc3b'
down_revision = '639d246bd433'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('filaments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('color_hex', sa.String(length=7), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('filaments', schema=None) as batch_op:
        batch_op.drop_column('color_hex')

    # ### end Alembic commands ###
